perf: Pack the state and future of unfolds in the same memory
rust-lang/futures-rs pull request #2283
Opened 2020-12-08 09:41 UTC by Marwes

cc https://github.com/rust-lang/futures-rs/pull/2268#discussion_r532011280

2020-12-08 10:09 UTC, taiki-e reviewed
Thanks! This looks good to me aside from a few nits.

2020-12-08 10:09 UTC, taiki-e commented on futures-util/src/sink/unfold.rs
> +            StateProjOwn::Future(_) | StateProjOwn::Empty => unreachable!()
```suggestion
            StateProjOwn::Future(_) => panic!("poll_ready not called first"),
            StateProjOwn::Empty => unreachable!()
```

nit: `StateProjOwn::Empty` is really unreachable unless closure panics and the user catch it, but `StateProjOwn::Future` can be reached if the user makes a mistake. A different panic message may be useful.

2020-12-08 10:09 UTC, taiki-e commented on futures-util/src/stream/unfold.rs
> +        matches!(self.state, State::Empty)
`matches!` macro is not available in our MSRV (1.37). Could you replace it with `match` or `if let`?

2020-12-08 10:09 UTC, taiki-e commented on futures-util/src/stream/unfold.rs
> +        if matches!(&*this.state, State::Value(_)) {
Same here

2020-12-08 23:28 UTC, taiki-e commented on futures-util/src/sink/unfold.rs
> +                result
```suggestion
                match ready!(future.poll(cx)) {
                    Ok(state) => {
                        this.state.set(State::Value(state));
                        Ok(())
                    }
                    Err(err) => Err(err),
                }
```

2020-12-09 11:04 UTC, Marwes commented
Had to updated this to manual pin projections due to https://github.com/rust-lang/futures-rs/pull/2273 .

2020-12-13 15:59 UTC, taiki-e requested changes
Thanks. The implementation LGTM, but seems CI is still failed. Could you fix it? (probably you need to replace `std` with `core` in `unfold_state.rs`)

In addition, there are many irrelevant format changes in `lib.rs`, could you remove them?

2020-12-25 05:04 UTC, taiki-e commented on futures-util/src/unfold_state.rs
> +use std::pin::Pin;
```suggestion
use core::pin::Pin;
```

2020-12-25 05:04 UTC, taiki-e commented on futures-util/src/unfold_state.rs
> +                match std::mem::replace(self.get_unchecked_mut(), UnfoldState::Empty) {
```suggestion
                match core::mem::replace(self.get_unchecked_mut(), UnfoldState::Empty) {
```

2020-12-25 05:04 UTC, taiki-e commented on futures-util/src/unfold_state.rs
> +                    _ => std::hint::unreachable_unchecked(),
```suggestion
                    _ => core::hint::unreachable_unchecked(),
```

2020-12-25 16:55 UTC, piegamesde commented on futures-util/src/sink/unfold.rs
> +se crate::unfold_state::UnfoldState;
Typo?

2020-12-26 04:23 UTC, taiki-e approved these changes

2020-12-26 04:25 UTC, merged